name: cs486-assignment11-edwardshturman

services:
  app:
    build: .
    ports:
      - "8081:8081"
    environment:
      URL: ${URL}
    healthcheck:
      test: curl http://app:8081
      timeout: 10s
      interval: 1s
      retries: 10
